Feature/issue 233  new feature new role create and core usage
TC-netw4ppl/website pull request #247
Opened 2022-10-14 13:35 UTC by mathisfchx

### Description
ROLE V2

## Issues fixed
List of related issues that are fixed by this PR :

- Closed #122
- Closed #143
- Closed #242
- Closed #233

### Feature Checklist
- [x] Cytoscape
- [x] Person/Index
- [x] Person/Filter
- [x] Person/Create
- [x] Person/Edit
- [x] Person/Delete
- [x] Relation/Index
- [x] Relation/Filter
- [x] Relation/Create
- [x] Relation/Edit
- [x] Relation/Delete
- [x] Duplicates/Index
- [x] Duplicates/Filter
- [ ] Duplicates/Create
- [ ] Duplicates/Edit
- [ ] ManageList/Delete
- [ ] ManageList/Create
- [ ] ManageList/Edit
- [ ] ManageField/Index
- [ ] ManageField/Create
- [ ] ManageField/Edit
- [ ] ManageField/Delete
- [ ] ApiList
- [ ] Crews
- [ ] Users

2022-10-14 15:06 UTC, lduf requested changes
Please, consider the following :

2022-10-14 15:06 UTC, lduf commented on src/resources/views/roles/index.blade.php
> +                @if (env("APP_DEBUG"))
❤️

2022-10-14 17:26 UTC, lduf commented
fixes #248

2022-10-14 18:13 UTC, lduf commented
Add a way to match 
route_controller and route_policy

-> add an attribute into model

If the attribute is defined then use the matching options. Else use the controller_route

2022-10-17 12:54 UTC, mathisfchx reviewed
🌍

2022-10-17 12:59 UTC, lduf approved these changes
🌍

2022-10-17 12:59 UTC, merged