Feature/issue 150  Add Event V0.5 feature
TC-netw4ppl/website pull request #296
Opened 2022-10-28 13:41 UTC by lduf

### Description
User can : create, update, view, viewAny events
Event is considered as a list

- Create some artisan command to handle theses new feature.
- Debug some cytoscape error (issues with role)
- Debug Create link on a new team (no more blank fields)

Please run the following : 
```
php artisan migrate --seed
php permissions:update
php lists:update 
```

## Issues fixed
List of related issues that are fixed by this PR :

#149
#150
#151

### Checklist
- [ ] Compiling
- [ ] Code factoring (comments, indent...)
- [ ] Documentation (net4p Doc, Readme...)

### Feature Checklist
- [ ] Cytoscape
- [ ] Person/Index
- [ ] Person/Filter
- [ ] Person/Create
- [ ] Person/Edit
- [ ] Person/Delete
- [ ] Relation/Index
- [ ] Relation/Filter
- [ ] Relation/Create
- [ ] Relation/Edit
- [ ] Relation/Delete
- [ ] Duplicates/Index
- [ ] Duplicates/Filter
- [ ] Duplicates/Create
- [ ] Duplicates/Edit
- [ ] ManageList/Delete
- [ ] ManageList/Create
- [ ] ManageList/Edit
- [ ] ManageField/Index
- [ ] ManageField/Create
- [ ] ManageField/Edit
- [ ] ManageField/Delete
- [ ] ApiList
- [ ] Crews
- [ ] Users

2022-10-31 16:03 UTC, lduf commented
@mathisfchx  please try the following features (check the checkbox if it's working): 

- [ ] create a new team
- [ ] create a new form (with the event list field)
- [ ] create a new event
- [ ] add several person 
- [ ] add relation using : add everyone from the same event (on from or on to)
- [ ] add another person
- [ ] add relation (classic way : you choose 2 people)

2022-11-01 08:55 UTC, mathisfchx requested changes

2022-11-01 08:55 UTC, mathisfchx commented on src/database/migrations/jsonDataset/roles.json
> +            "event.show",
```suggestion
            
```

2022-11-01 08:55 UTC, mathisfchx commented on src/database/migrations/jsonDataset/roles.json
> +            "event.index",
```suggestion

```

2022-11-01 08:55 UTC, mathisfchx commented on src/app/Http/Controllers/LinkController.php
>          Link::create($link);
validation failed if no event = bad

2022-11-01 08:55 UTC, mathisfchx commented on src/app/Models/ListControl.php
> +        return self::orderBy('short')->pluck('short', 'id');
??

2022-11-01 08:55 UTC, mathisfchx commented on src/resources/views/event/create.blade.php
> +                            @php($list = \App\Models\ListCountry::list())
::list() in src/app/Models/ListControl.php = to generalize

2022-11-01 08:55 UTC, mathisfchx commented on src/resources/views/event/create.blade.php
> +                        <!--  start date SECTION  -->
section are not corresponding (also check the others)

2022-11-01 08:55 UTC, mathisfchx commented on src/resources/views/event/edit.blade.php
> +                            @php($list = \App\Models\ListCountry::list())
same thing (generalize)

2022-11-01 08:55 UTC, mathisfchx commented on src/resources/views/event/edit.blade.php
> +                        <!--  start date SECTION  -->
checks section names

2022-11-01 09:27 UTC, lduf commented on src/database/migrations/jsonDataset/roles.json
> +            "event.show",
done

2022-11-01 09:27 UTC, lduf commented on src/database/migrations/jsonDataset/roles.json
> +            "event.index",
done

2022-11-01 09:47 UTC, mathisfchx commented
⚠️ in update:list add a --seed for event type ⚠️

2022-11-01 11:15 UTC, lduf commented on src/app/Http/Controllers/LinkController.php
>          Link::create($link);
done

2022-11-01 12:53 UTC, lduf commented
> 

Already done 😆

2022-11-01 17:45 UTC, mathisfchx approved these changes
🌍

2022-11-01 17:45 UTC, merged